### ISSUE TITLE
`Exit status 1` for dotfile

### ISSUE THREAD

**Issue by babramczyk** [nikitavoloboev/gitupdate#9]
### To reproduce

1. Make change to file with path `.zshrc` (i.e., in root of git repo)
2. `$ gitupdate`

Result:

```console
2020/12/16 19:09:56 exit status 1
```

**Comment by nikitavoloboev** [comment]
I need to add some error catching. Not sure what caused this error to happen. The command will essentially `git add .`, `git commit -m ..` (with file names) and `git push`.

If you try run it yourself and see if any of the commands throws error, you will know the cause. Sometimes it's due to git .lock file being present.

**Comment by babramczyk** [comment]
I think the problem is the [logic here](https://github.com/nikitavoloboev/gitupdate/blob/f21ef69f01ce409b0a7fce533e8c75aa48a9936a/main.go#L79), where it's trying to strip the filename extension. For a file that starts with `.` like `.zshrc`, there's going to be nothing left for that part of the commit message, which is what I would imagine is causing the problem.

Not sure on the solution -- maybe just strip any leading periods off of filenames before doing that logic.

Happy to submit a PR at some point, but to be honest I have no idea what I'm doing in Go and might not have time soon to learn it.

**Comment by nikitavoloboev** [comment]
I'll try it out, thanks. Go is simple (https://news.ycombinator.com/item?id=25646909). 

I'll try fix this soonish, if not, I am open to PR :)
